zf-commons/zfc-user/2015-01-08.yaml
https://github.com/ZF-Commons/ZfcUser/issues/550
=> ZfcUser XSS vulnerability

monolog/monolog/2014-12-29-1.yaml
A low severity issue, but it would be nice to get this into the checks.
=> Add fix from monolog

contao/core/2014-02-13.yaml, contao/core/2014-04-07.yaml, contao/core/CVE-2015-0269.yaml
This PR adds the Contao Open Source CMS vulnerabilities of the last 14 months.
=> Add the Contao vulnerabilities

namshi/jose/2015-02-19.yml
Hey guys, we just found a vulnerability in one of our libraries and would like it to be pushed here so that more users will realize they need to upgrade :)
cheers!
We will also publish a post soon with a longer explanations so I will change the `link` in another PR, for now its just a link to the commit that fixes the issue.
=> added namshi/jose vulnerability

thelia/backoffice-default-template/2015-02-24-1.yaml, thelia/thelia/2015-02-24-1.yaml
The versions concerned by the security issue were not good.
=> change version for Thelia security issue

zendframework/zendframework/ZF2015-01.yaml, zendframework/zendframework/ZF2015-02.yaml
Thanks @Ocramius for the follow up: I forgot `zendframework/zendframework` in #52, this should fix it now.
=> Add ZF2015-02 for zendframework/zendframework too

firebase/php-jwt/2015-04-02.yaml, namshi/jose/2015-03-10.yaml
See https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/ for the announcement
=> Add the advisory for the firebase/php-jwt vulnerability

typo3/flow/2012-03-28.yaml, typo3/flow/CVE-2013-7082.yaml, typo3/neos/2015-03-28.yaml
This adds the existing security advisories for typo3/neos and typo3/flow to the security database.
=> Add Neos and Flow to security database

README.md, validator.php
added a note that running composer install is required.
=> Nicer error message if dependencies are not installed

zendframework/zend-diactoros/ZF2015-05.yaml
http://framework.zend.com/security/advisory/ZF2015-05
=> Add the advisory for ZF2015-05

oro/crm/2015-07-08.yaml, oro/platform/2015-07-08.yaml
@DimaSoroka Can you (or anyone else from Oro) please proofread?
=> add Oro Platform 1.7.4 and OroCRM 1.7.4

yiisoft/yii2/CVE-2015-5467.yaml
http://www.yiiframework.com/news/87/yii-2-0-5-is-released-security-fix/
=> Added Yii Framework 2 CVE-2015-5467

zendframework/zendframework/ZF2015-06.yaml, zendframework/zendframework1/ZF2015-06.yaml, zendframework/zendxml/ZF2015-06.yaml
- Affects zendframework/zendframework
- Affects zendframework/zendframework1
- Affects zendframework/zendxml
See http://framework.zend.com/security/advisory/ZF2015-06 for details.
=> Adds ZF2015-06 / CVE-2015-5161

cakephp/cakephp/2015-08-06.yaml
We had a new issue in the 2.x release series that warrants more visibility on.
=> Add new CakePHP issue.

twig/twig/2015-08-12.yaml
https://symfony.com/blog/security-release-twig-1-20-0
=> Add the security advisory for the Twig 1.20 release

doctrine/common/2015-08-31.yaml, doctrine/mongodb-odm-bundle/2015-08-31.yaml, doctrine/orm/2015-08-31.yaml, namshi/jose/2015-02-19.yaml, oro/crm/2015-07-08.yaml, oro/platform/2015-07-08.yaml
Also, this is reason 8400347509437 for YAML being a shitty configuration format.
Fitting quote:
> The story so far:
> In the beginning the Universe was created.
> This has made a lot of people very angry and been widely regarded as a bad move.
=> Correcting YAML syntax for branch names

silverstripe/framework/SS-2014-017-1.yaml
I'll add the other security releases later on. Give me a little bit time.
=> Adding SS-2014-017

typo3/cms/2015-09-08-1.yaml, typo3/cms/CVE-2015-5956.yaml
https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2015-008/
https://typo3.org/teams/security/security-bulletins/typo3-core/typo3-core-sa-2015-009/
=> Add new TYPO3 CMS security advisories

silverstripe/framework/SS-2015-012-1.yaml
Are the branches okay like this?
=> SS 2015 012

silverstripe/framework/SS-2015-011-1.yaml, silverstripe/framework/SS-2015-014-1.yaml, silverstripe/userforms/SS-2015-018-1.yaml
Final PR for the remaining SS security advisories. Thank you for your patience :)
=> Silverstripe security advisories

silverstripe/framework/SS-2014-015-1.yaml
the branches have been mixed up in this file. I fixed this quickly.
=> fixing branches for SS-2014-015

codeigniter/framework/2015-10-31-1.yaml
This adds the existing vulnerability in CodeIgniter 3.
=> Add XSS in CodeIgniter

zendframework/zend-captcha/ZF2015-09.yaml, zendframework/zendframework/ZF2015-09.yaml, zendframework/zendframework1/ZF2015-09.yaml
see http://framework.zend.com/security/advisory/ZF2015-09
I was not completely sure about the lower bounds of affected versions (maybe @weierophinney or @Ocramius can confirm them).
=> add ZF2015-09 advisory

joomla/session/2015-12-14.yaml
Ref: https://developer.joomla.org/security-centre/637-20151205-session-remote-code-execution-vulnerability.html
=> Add joomla/session RCE vulnerability

composer/composer/CVE-2015-8371.yaml
entry at cve registry should soon be updated to include the infos, too.
No experience how long they need
=> add CVE-2015-8371.yaml

silverstripe/framework/SS-2015-028-1.yaml, silverstripe/framework/SS-2016-002-1.yaml, silverstripe/framework/SS-2016-003-1.yaml
Adding the latest SilverStripe notices in.
=> Latest silverstripe security notices

shopware/shopware/2016-04-11.yaml
Reference: http://community.shopware.com/_detail_1918.html
=> Add shopware/shopware Unauthenticated Remote Code Execution Vulnerability

composer.json, validator.php
The validator takes a little while to run without any output, this adds a progress bar and formats the result (status message and table of any issues).
=> Add formatting to the validator

zendframework/zendframework1/ZF2016-01.yaml
My first try. Hopefully not my last contribution :+1:
=> adding ZF2016-01 advisory

shopware/shopware/CVE-2016-3109.yaml
Reference: 
- http://seclists.org/bugtraq/2016/Apr/127
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-3109
=> Add CVE identifier for shopware/shopware Vulnerability

typo3/cms/2016-02-16-1.yaml, typo3/cms/2016-02-16-2.yaml, typo3/cms/2016-02-16-3.yaml, typo3/cms/2016-02-16-4.yaml, typo3/cms/2016-02-23-1.yaml, typo3/cms/2016-02-23-2.yaml, typo3/cms/2016-02-23-3.yaml, typo3/cms/2016-02-23-4.yaml, typo3/cms/2016-04-12-1.yaml, typo3/cms/2016-04-12-2.yaml, typo3/cms/2016-04-12-3.yaml, typo3/cms/2016-04-12-4.yaml
Added all missing TYPO3 CMS vulnerabilites from 2016
=> Added missing TYPO3 CMS vulnerabilites from 2016

guzzlehttp/guzzle/CVE-2016-5385.yaml
=> Add CVE-2016-5385 for guzzlehttp/guzzle

zendframework/zendframework1/ZF2016-03.yaml
Potential SQL injection in ORDER and GROUP functions of ZF1
=> adding ZF2016-03

cakephp/cakephp/2015-11-05.yaml
I was off by one in one situation and all of 2.5.x is vulnerable.
Refs #116
=> Fix ranges in CakePHP range.

typo3/cms/2016-09-14-1.yaml, typo3/cms/2016-09-14-2.yaml
Added TYPO3 CMS vulnerabilities TYPO3-CORE-SA-2016-021 and TYPO3-CORE-SA-2016-022
=> Added TYPO3 CMS vulnerabilities TYPO3-CORE-SA-2016-021 and -022

codeigniter/framework/2016-07-26-1.yaml
The validator says:
> Invalid branch name "3.0-stable"
But I don't know how to do.
=> Add SQLi in CodeIgniter

adodb/adodb-php/CVE-2016-4855.yaml
I'm not sure if my provied link https://github.com/ADOdb/ADOdb/issues/274 or this on https://jvn.jp/en/jp/JVN48237713/index.html is favored :/
=> adodb/adodb-php CVE-2016-4855

simplesamlphp/simplesamlphp/201612-01.yaml
Reverts FriendsOfPHP/security-advisories#183
=> Revert "simplesamlphp SSPSA 201612-01: Incorrect signature validation"

simplesamlphp/simplesamlphp-module-infocard/201612-03.yaml
Incorrect sigature verification
=> simplesamlphp/simplesamlphp-module-infocard 201612-03

drupal/core/CVE-2017-6381.yaml, drupal/core/CVE-2017-6919.yaml, drupal/drupal/CVE-2017-6381.yaml, drupal/drupal/CVE-2017-6919.yaml
Also fixes a minor typo for CVE-2017-6381
=> CVE-2017-6919 (Drupal 8.3.1 / 8.2.8)

amphp/artax/2017-05-09.yaml
* https://twitter.com/asyncphp/status/862033196824842246
* https://github.com/amphp/artax/commit/accdadaf78f7a43305c3a97d6a964bbc550a555d
=> Add Artax cookie leakage

drupal/core/CVE-2017-6920.yaml, drupal/core/CVE-2017-6921.yaml, drupal/core/CVE-2017-6922.yaml, drupal/drupal/CVE-2017-6920.yaml, drupal/drupal/CVE-2017-6921.yaml, drupal/drupal/CVE-2017-6922.yaml
https://www.drupal.org/SA-CORE-2017-003
* CVE-2017-6920
* CVE-2017-6921
* CVE-2017-6922
=> Drupal advisory SA-CORE-2017-003

contao-components/mediaelement/CVE-2016-4567.yaml, contao/core-bundle/CVE-2017-10993.yaml, contao/core/2014-02-13.yaml, contao/core/2014-04-07.yaml, contao/core/CVE-2015-0269.yaml, contao/core/CVE-2016-4567.yaml, contao/core/CVE-2017-10993.yaml
This PR updates the Contao data and adds CVE-2017-10993.
=> Update the Contao data and add CVE-2017-10993

ezsystems/ezpublish-legacy/2017-08-22-1.yaml
Hi! This is eZ Systems' first PR here. We want to use this repo actively from now on. Because of the delay in getting CVEs we intend to publish issues here as soon as we make them public on our end, and update them later when we get the CVEs.
http://share.ez.no/community-project/security-advisories/ezsa-2017-005-xss-issue-in-search
=> EZSA-2017-005: XSS issue in search

typo3/cms/2017-09-05-1.yaml, typo3/cms/2017-09-05-2.yaml, typo3/cms/2017-09-05-3.yaml, typo3/cms/2017-09-05-4.yaml
Fix link to TYPO3-Security Announcement 2017-004
=> 20170911 typo3 sa september

shopware/shopware/2017-06-22.yaml
=> Shopware Security Update 06/2017

simplesamlphp/saml2/201801-01.yaml, simplesamlphp/simplesamlphp-module-infocard/CVE-2017-12874.yaml, simplesamlphp/simplesamlphp/201710-01.yaml, simplesamlphp/simplesamlphp/201801-02.yaml, simplesamlphp/simplesamlphp/201801-03.yaml, simplesamlphp/simplesamlphp/CVE-2017-12867.yaml, simplesamlphp/simplesamlphp/CVE-2017-12868.yaml, simplesamlphp/simplesamlphp/CVE-2017-12869.yaml, simplesamlphp/simplesamlphp/CVE-2017-12870.yaml, simplesamlphp/simplesamlphp/CVE-2017-12871.yaml, simplesamlphp/simplesamlphp/CVE-2017-12872.yaml, simplesamlphp/simplesamlphp/CVE-2017-12873.yaml
Additionally, set CVE numbers for those issues that got one.
=> Add all missing SimpleSAMLphp advisories

padraic/file_get_contents/CVE-2016-5385.yaml
=> Add CVE-2016-5385 for Humbug/file_get_contents

padraic/file_get_contents/CVE-2016-5385.yaml
=> #251 added branch reference to CVE-2016-5385 manifest

asymmetricrypt/asymmetricrypt/2017-11-20.yaml, pagarme/pagarme-php/2017-11-20.yaml, stormpath/sdk/2017-11-20.yaml, titon/framework/2017-11-20.yaml
* https://github.com/Cosmicist/AsymmetriCrypt/issues/4
* https://github.com/pagarme/pagarme-php/issues/29
* https://github.com/stormpath/stormpath-sdk-php/issues/132
* https://github.com/titon/framework/issues/93
=> Add advisories for (abandoned?) projects with unfixed vulnerabilities.

ezsystems/ezpublish-legacy/2017-08-22-1.yaml, ezsystems/ezpublish-legacy/2018-02-26-1.yaml
Add CVE to existing advisory EZSA-2017-005
Add advisory EZSA-2018-001
=> eZ Systems update february

simplesamlphp/simplesamlphp/201803-01.yaml
Reverts FriendsOfPHP/security-advisories#265
=> Revert "Create 201803-01.yaml"

illuminate/encryption/2018-03-30-1.yaml, laravel/framework/2018-03-30-1.yaml
As mentioned by Taylor Otwell, https://medium.com/@taylorotwell/laravel-security-release-5-6-15-and-5-5-40-56f1257933a0
=> Add Laravel weak comparison encryption failure exploit

magento/magento2ce/2016-07-19.yaml
Ref: https://github.com/FriendsOfPHP/security-advisories/pull/161#issuecomment-402080141
=> Exclude Magento-CE 2.2 as per #161 discussion

magento/product-community-edition/2016-07-19.yaml
Ref: https://github.com/FriendsOfPHP/security-advisories/pull/306#pullrequestreview-134243916
=> Update CVE-2016-6485 times

README.md
=> Be more clear about the time zone of `time`

robrichards/xmlseclibs/2018-09-27.yaml
=> add possible XPath injection on xmlseclibs

drupal/core/2018-10-17-1.yaml, drupal/core/2018-10-17-2.yaml, drupal/core/2018-10-17-3.yaml, drupal/core/2018-10-17-4.yaml, drupal/core/2018-10-17-5.yaml, drupal/drupal/2018-10-17-1.yaml, drupal/drupal/2018-10-17-2.yaml, drupal/drupal/2018-10-17-3.yaml, drupal/drupal/2018-10-17-4.yaml, drupal/drupal/2018-10-17-5.yaml
from https://www.drupal.org/sa-core-2018-006
=> Drupal Core - Multiple Vulnerabilities - SA-CORE-2018-006

phpoffice/phpspreadsheet/CVE-2018-19277.yaml
=> XXE Vulnerability in PHPSpreadsheet

phpoffice/phpexcel/CVE-2018-19277.yaml
=> XXE Vulnerability in PHPExcel

magento/magento1ce/2018-11-28.yaml, magento/magento1ee/2018-11-28.yaml, magento/product-community-edition/2018-11-28.yaml
SUPEE-10975, v2.1.16 and v2.2.7
=> Magento's releases from 2018-11-28

ua-parser/uap-php/2018-12-14.yaml
Relevant upstream change: https://github.com/ua-parser/uap-core/pull/363
Relevant project change: https://github.com/ua-parser/uap-php/commit/947f80b39130c83a3d1c75900ac1b58828ed8aef
Relevant updated version: https://github.com/ua-parser/uap-php/releases/tag/v3.8.0
=> DoS in uap-php

typo3/cms-core/2019-01-22-1.yaml, typo3/cms-core/2019-01-22-2.yaml, typo3/cms-core/2019-01-22-3.yaml, typo3/cms-core/2019-01-22-4.yaml, typo3/cms-core/2019-01-22-5.yaml, typo3/cms-core/2019-01-22-6.yaml, typo3/cms-core/2019-01-22-7.yaml, typo3/cms-core/2019-01-22-8.yaml, typo3/cms/2019-01-22-1.yaml, typo3/cms/2019-01-22-2.yaml, typo3/cms/2019-01-22-3.yaml, typo3/cms/2019-01-22-4.yaml, typo3/cms/2019-01-22-5.yaml, typo3/cms/2019-01-22-6.yaml, typo3/cms/2019-01-22-7.yaml, typo3/cms/2019-01-22-8.yaml
+ autogenerated by https://github.com/TYPO3/darth
+ `bin/darth security 8.7.23,9.5.4`
=> [TASK] Add security advisories for TYPO3's January 2019 releases

drupal/core/CVE-2019-6338.yaml, drupal/core/CVE-2019-6339.yaml, drupal/drupal/CVE-2019-6338.yaml, drupal/drupal/CVE-2019-6339.yaml
=> fix Drupal 6.6 version constraint

league/commonmark/2019-03-21.yaml
See https://github.com/thephpleague/commonmark/issues/353
=> Add XSS vulnerability in league/commonmark

zendframework/zend-developer-tools/ZF2019-01.yaml
See: https://framework.zend.com/security/advisory/ZF2019-01
=> Add ZF2019-01 (zend-developer-tools 1.2.2)

contao/core-bundle/CVE-2019-11512.yaml
This PR adds CVE-2019-11512 to contao/core-bundle.
=> Add Contao CVE-2019-11512

magento/magento1ce/CVE-2019-7139.yaml, magento/magento1ee/CVE-2019-7139.yaml, magento/product-community-edition/CVE-2019-7139.yaml
=> Magento - CVE-2019-7139

silverstripe/framework/CVE-2019-12246.yaml, silverstripe/graphql/CVE-2019-12437.yaml, silverstripe/registry/CVE-2019-12149.yaml, silverstripe/restfulserver/CVE-2019-12149.yaml
=> Add CVE-2019-12246, CVE-2019-12437, CVE-2019-12149 for SilverStripe

symfony/cache/CVE-2019-10912.yaml
see https://github.com/FriendsOfPHP/security-advisories/pull/390#discussion_r293738373
=> fix lower version boundary

studio-42/elfinder/CVE-2019-9194.yaml
Add Studio-42/elFinder latest CVE
=> Add CVE-2019-9194

robrichards/xmlseclibs/CVE-2019-3465.yaml
More details: https://simplesamlphp.org/security/201911-01
=> add CVE-2019-3465

symfony/symfony/CVE-2019-11325.yaml, symfony/symfony/CVE-2019-18886.yaml, symfony/symfony/CVE-2019-18887.yaml, symfony/symfony/CVE-2019-18888.yaml, symfony/symfony/CVE-2019-18889.yaml
added missing CVEs to symfony/symfony
fixes: #422
=> added Symfony 2019-11 CVEs to symfony/symfony

simplesamlphp/simplesamlphp/2019-11-19.yaml
=> Fix the upper bound for the simplesamlphp vulnerability

endroid/qr-code-bundle/2019-12-22.yaml
QR Code Bundle vulnerability (fixed)
=> QR Code Bundle vulnerability (fixed)

ezsystems/ezfind-ls/2019-05-23-1.yaml, ezsystems/ezplatform-admin-ui-assets/2019-07-04-1.yaml, ezsystems/ezplatform-admin-ui/2019-04-03-1.yaml, ezsystems/ezplatform-user/2019-04-03-1.yaml, ezsystems/ezplatform/2019-06-27-1.yaml, ezsystems/ezplatform/2019-09-03-1.yaml, ezsystems/ezplatform/2019-09-03-2.yaml
I'm sorry to say I haven't been updating our advisories here last year. This PR is to bring us up to date. Better late than never, but I will get back to doing PRs here as soon as the advisories are made public.
=> ezsystems 2019 issues

ezsystems/ezplatform-kernel/2020-05-20-1.yaml, ezsystems/ezpublish-kernel/2020-05-20-1.yaml
https://ezplatform.com/security-advisories/ezsa-2020-004-object-injection-in-siteaccessmatchlistener
=> Add ezsystems issue 2020-004

yiisoft/yii2/CVE-2020-15148.yaml
Possible remote code execution via unserialize() on user input containing specially crafted string.
- https://www.yiiframework.com/news/303/yii-2-0-38
- https://github.com/yiisoft/yii2/security/advisories/GHSA-699q-wcff-g9mj
- CVE-2020-15148
- Fixed in 2.0.38
=> Yii 2: Unsafe unserialize (CVE-2020-15148)

smarty/smarty/CVE-2018-16831.yaml
It looks like there is another CVE for the same vulnerability as CVE-2018-13982.
=> Add CVE-2018-16831

drupal/core/2020-11-25.yaml, drupal/drupal/2020-11-25.yaml
Unable to parse these files using js-yaml
=> Fix YAML duplicate keys for 47698cc

twig/twig/CVE-2015-7809.yaml, twig/twig/CVE-2019-9942.yaml
See:
* https://nvd.nist.gov/vuln/detail/CVE-2019-9942
* https://nvd.nist.gov/vuln/detail/CVE-2015-7809
=> Add CVE identifiers to twig/twig advisories

phpoffice/phpspreadsheet/CVE-2020-7776.yaml
XSS Vulnerability in HTML Writer, resolved in Release 1.16.0
=> CVE-2020-7776

.github/workflows/php.yaml
I usually forget to run this, so it would be good if CI did it automatically.
=> Configure CI to run the validator

laravel/framework/2021-01-14-1.yaml
Fixes a vulnerability in the QueryBuilder due to unexpected bindings.
=> added laravel/framework entry

mautic/core/CVE-2020-35124.yaml, mautic/core/CVE-2020-35125.yaml, mautic/core/CVE-2021-3142.yaml
I have created a PR according to the instructions to add [Mautic](https://github.com/mautic/mautic) and included three recent CVEs, however I am unable to have it pass the validation due to the naming of our main branch (features).
Would appreciate some guidance on how to proceed!
=> Add mautic and recent CVEs

smarty/smarty/CVE-2021-26119.yaml, smarty/smarty/CVE-2021-26120.yaml
See https://github.com/smarty-php/smarty/blob/master/CHANGELOG.md#3139---2021-02-17
=> New Smarty CVEs

symbiote/silverstripe-queuedjobs/CVE-2021-27938.yaml
https://www.silverstripe.org/download/security-releases/cve-2021-27938
=> CVE-2021-27938 - XSS in CreateQueuedJobTask

typo3/swiftmailer/2017-01-06.yaml
=> Add typo3/swiftmailer advisory

typo3/flow/2012-03-28.yaml, typo3/flow/2015-11-23.yaml, typo3/flow/2017-04-12.yaml, typo3/flow/CVE-2013-7082.yaml
This updates the links for some existing advisories and adds a
missing advisory.
=> Update typo3/flow advisories

typo3/neos/2015-03-28.yaml, typo3/neos/2015-11-23.yaml, typo3/neos/2019-06-17.yaml
This updates the links for existing advisories and adds a missing
advisory.
=> Update typo3/neos advisories

illuminate/database/2021-04-28.yaml, laravel/framework/2021-04-28.yaml
https://blog.laravel.com/security-sql-injection-in-sql-server-limit-offset
=> Add Laravel advisory

klaviyo/magento2-extension/2021-05-25-1.yaml
Via a public reclaim url private data could be exposed to the web
More information https://gist.github.com/JeroenBoersma/f5864a45e3df63b198a57abdff366df2
=> Klaviyo Magento 2 extension before 3.0.0

league/flysystem/2021-06-24.yaml
https://github.com/thephpleague/flysystem/security/advisories/GHSA-9f46-5r25-5wfm
=> Added security advisory for league/flysystem.

mautic/core/CVE-2021-27909.yaml, mautic/core/CVE-2021-27910.yaml, mautic/core/CVE-2021-27911.yaml, mautic/core/CVE-2021-27912.yaml, mautic/core/CVE-2021-27913.yaml
Adding CVE-2021-27909, CVE-2021-27910, CVE-2021-27911, CVE-2021-27912 and CVE-2021-27913.
=> Add CVEs relating to Mautic 4.0.0 and 3.3.4

drupal/core/2021-05-26.yaml, drupal/drupal/2021-05-26.yaml
Left a copy paste error in my last PR. Here's a fix
=> Update title of Drupal SAs

symfont/process/2021-09-10.yml
First time, not sure how to correctly add this typosquatting malware to this project. 
Related to https://github.com/FriendsOfPHP/security-advisories/issues/587
=> Added symfont/process

README.md
Hi, small update referencing https://github.com/symfony/symfony-docs/pull/16356
=> Update Checking Security Vulnerabilities doc part

mustache/mustache/CVE-2022-0323.yaml
https://github.com/bobthecow/mustache.php/releases/tag/v2.14.1
=> Add CVE-2022-0323 mustache/mustache

enshrined/svg-sanitize/CVE-2022-23638.yaml
=> Add CVE-2022-23638.

rudloff/alltube/CVE-2022-0692.yaml
See https://github.com/Rudloff/alltube/security/advisories/GHSA-jmhf-9fj8-88gh
=> Add CVE-2022-0692

rudloff/alltube/CVE-2022-0768.yaml
See https://github.com/Rudloff/alltube/security/advisories/GHSA-r5hc-wm3g-hjw6
=> Add CVE-2022-0768

rudloff/alltube/CVE-2022-24739.yaml
See https://github.com/Rudloff/alltube/security/advisories/GHSA-75p7-527p-w8wp
=> Add CVE-2022-24739

smarty/smarty/CVE-2021-21408.yaml, smarty/smarty/CVE-2021-29454.yaml
https://github.com/smarty-php/smarty/security/advisories/GHSA-4h9c-v5vg-5m6m and https://github.com/smarty-php/smarty/security/advisories/GHSA-29gp-2c3m-3j6m
=> Add new smarty CVEs

validator.php
This is not a full validation for now, but it will catch most mistakes.
=> Add some validation of the CVE format

guzzlehttp/psr7/CVE-2022-24775.yaml, guzzlehttp/psr7/GHSA-q7rv-6hp3-vh96.yaml
I just requested a CVE from Github. I guess they will come back next week.
=> CVE-2022-24775: Guzzle PSR-7

composer/composer/CVE-2022-24828.yaml
See https://github.com/composer/composer/security/advisories/GHSA-x7cr-6qr6-2hh6.
=> Add CVE-2022-24828

guzzlehttp/guzzle/CVE-2022-31042.yaml, guzzlehttp/guzzle/CVE-2022-31043.yaml
CVEs are very much like buses!
=> Added more Guzzle CVEs

typo3/cms-core/CVE-2022-31046.yaml, typo3/cms-core/CVE-2022-31047.yaml, typo3/cms-core/CVE-2022-31048.yaml, typo3/cms-core/CVE-2022-31049.yaml, typo3/cms-core/CVE-2022-31050.yaml, typo3/cms/CVE-2022-31046.yaml, typo3/cms/CVE-2022-31047.yaml, typo3/cms/CVE-2022-31048.yaml, typo3/cms/CVE-2022-31049.yaml, typo3/cms/CVE-2022-31050.yaml
https://typo3.org/article/typo3-11511-and-10429-security-releases-published
=> Add security advisories for TYPO3's June 2022 releases

react/http/CVE-2022-36032.yaml
see https://github.com/advisories/GHSA-w3w9-vrf5-8mx8
=> add CVE-2022-36032 for react/http

.github/workflows/php.yaml, composer.json, symfont/process/2021-09-10.yaml, validator.php
This mostly upgrades the dependencies of the validator. In particular, using Composer 2 means we rely on the non-deprecated endpoints.
=> Upgrade the CI setup

api-platform/core/CVE-2023-25575.yaml
=> CVE-2023-25575

knplabs/knp-snappy/CVE-2023-28115.yaml
CVE-2023-28115
knplabs/knp-snappy 
https://github.com/advisories/GHSA-gq6w-q6wh-jggc
=> CVE-2023-28115

smarty/smarty/CVE-2023-28447.yaml
Add smarty vulnerability
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-28447 https://github.com/smarty-php/smarty/security/advisories/GHSA-7j98-h7fp-4vwj
=> Create smarty/smarty CVE-2023-28447.yaml

directmailteam/direct-mail/CVE-2023-50461.yaml, in2code/femanager/CVE-2023-50459.yaml, t3s/content-consent/CVE-2023-50462.yaml
* CVE-2023-50459 - `in2code/femanager`
* CVE-2023-50461 - `directmailteam/direct-mail`
* CVE-2023-50462 - `t3s/content-consent`
=> Added the latest TYPO3 extension security announcements

microweber/microweber/CVE-2023-6566.yaml
Reference: https://nvd.nist.gov/vuln/detail/CVE-2023-6566
=> Add CVE-2023-6566 for microweber/microweber

elijaa/phpmemcacheadmin/CVE-2023-6026.yaml
Reference: https://nvd.nist.gov/vuln/detail/CVE-2023-6026
=> Add CVE-2023-6026 for elijaa/phpmemcacheadmin

elijaa/phpmemcacheadmin/CVE-2023-6027.yaml
Reference: https://nvd.nist.gov/vuln/detail/CVE-2023-6027
=> Add CVE-2023-6027 for elijaa/phpmemcacheadmin

microsoft/microsoft-graph-core/CVE-2023-49283.yaml, microsoft/microsoft-graph/CVE-2023-49282.yaml
Reference: https://nvd.nist.gov/vuln/detail/CVE-2023-49282
=> Add CVE-2023-49282 and CVE-2023-49283 for microsoft/microsoft-graph

amphp/http-client/CVE-2024-2653.yaml, amphp/http/CVE-2024-2653.yaml
- https://github.com/amphp/http-client/security/advisories/GHSA-w8gf-g2vq-j2f4
- https://github.com/amphp/http/security/advisories/GHSA-qjfw-cvjf-f4fm
=> Add CVE-2024-2653

timber/timber/CVE-2024-29800.yaml
see https://github.com/timber/timber/security/advisories/GHSA-6363-v5m4-fvq3
=> add CVE-2024-29800 for timber/timber

in2code/powermail/CVE-2024-47047.yaml
Add CVE-2024-47047 for TYPO3 extension "powermail". 
Advisory: https://typo3.org/security/advisory/typo3-ext-sa-2024-007
=> Add CVE-2024-47047

laravel/framework/CVE-2024-13918.yaml, laravel/framework/CVE-2024-13919.yaml
Security advisories:
* https://github.com/sbaresearch/advisories/tree/public/2024/SBA-ADV-20241209-01_Laravel_Reflected_XSS_via_Request_Parameter_in_Debug-Mode_Error_Page
* https://github.com/sbaresearch/advisories/tree/public/2024/SBA-ADV-20241209-02_Laravel_Reflected_XSS_via_Route_Parameter_in_Debug-Mode_Error_Page
=> Add CVE-2024-13918 and CVE 2024 13919: Laravel Reflected XSS via Request/Route Parameter in Debug-Mode Error Page

dnadesign/silverstripe-elemental/CVE-2025-25197.yaml, silverstripe/framework/CVE-2025-30148.yaml, silverstripe/framework/SS-2025-001.yaml
Fixing commit dates in https://github.com/FriendsOfPHP/security-advisories/pull/747 where month and day was switched
=> Fix dates in silverstripe vulnerabilities
