FriendsOfPHP/security-advisories

zendframework/zend-db/ZF2015-02.yaml, zendframework/zend-session/ZF2015-01.yaml
All ZendFramework files name uses their internal ID name, so I went for it.
Please, do tell if ZF2015-02.yaml should be renamed as CVE-2015-0270.yaml.
=> Add ZF2015-02

zendframework/zend-db/ZF2014-06.yaml, zendframework/zend-db/ZF2015-02.yaml, zendframework/zend-ldap/ZF2014-05.yaml, zendframework/zend-session/ZF2015-01.yaml, zendframework/zendframework/ZF2014-05.yaml, zendframework/zendframework/ZF2014-06.yaml, zendframework/zendframework/ZF2015-01.yaml, zendframework/zendframework/ZF2015-02.yaml, zendframework/zendframework1/ZF2014-05.yaml, zendframework/zendframework1/ZF2014-06.yaml
@stof [noticed](https://github.com/FriendsOfPHP/security-advisories/pull/55#discussion_r26372431) my last clean up was too overwhelming, so I reverted it (except for ZF2015-03 as accurately [pointed](https://github.com/FriendsOfPHP/security-advisories/pull/55#discussion_r26327553) by @xabbuh).
This is a revert of the offending changes, with more CVE and components documented for theses issues.
=> Review last ZF issues

symfony/http-foundation/CVE-2015-2309.yaml, symfony/symfony/CVE-2015-2309.yaml
The database incorrectly reports version 2.5.11 as affected, but that version has been fixed.
Check comments on http://symfony.com/blog/cve-2015-2309-unsafe-methods-in-the-request-class
=> Fix affected versions of symfony / http-foundation for CVE-2015-2309

zendframework/zend-http/ZF2015-04.yaml, zendframework/zend-mail/ZF2015-04.yaml, zendframework/zendframework/ZF2015-04.yaml
Maybe @Ocramius could ack this proposal? After a quick look, I believe ZF1 is also partly affected, is a fix also on its way, should we document zendframework/zendframework1 as affected?
=> Add ZF2015-04/CVE-2015-3154 about zendframework

yiisoft/yii2-bootstrap/CVE-2015-3397.yaml, yiisoft/yii2-dev/CVE-2015-3397.yaml, yiisoft/yii2-gii/CVE-2015-3397.yaml, yiisoft/yii2-jui/CVE-2015-3397.yaml, yiisoft/yii2/CVE-2015-3397.yaml
Affected packages:
- yiisoft/yii2 `<2.0.4`
- yiisoft/yii2-dev `<2.0.4`
- yiisoft/yii2-bootstrap `<2.0.4`
- yiisoft/yii2-gii `<2.0.4`
- yiisoft/yii2-jui `<2.0.4`
Announcement: http://www.yiiframework.com/news/86/yii-2-0-4-is-released/
The fixing commit: https://github.com/yiisoft/yii2/commit/78d3a856d3b2691a6071d23acd0f75cafe3808e0
=> Create CVE-2015-3397 for yii2 and extensions

pusher/pusher-php-server/2015-05-13.yaml
The announcement was not done on a public URL but by sending a mail to their customers actually.
I used the URL of the gist describing the way to apply the same validation for people writing their own implementations.
@leggetter @WillSewell is there a better URL to be used in the advisory ?
=> Add the advisory for the pusher-php-server vulnerability

laravel/socialite/2015-07-23.yaml, laravel/socialite/2015-08-03.yaml
The first vulnerability was in the fact that the generated state wasn't actually random and the user could work it out from their session.
The second vulnerability prevents two things. The first part of this fix prevents guessing the state through multiple attempts, and the second prevents an attacker from gaining access by not sending a session cookie and then sending no state as a query parameter - in this condition, you could bypass state checking all together because the check to check the state wasn't empty was missing so emtpy === empty was passing...
=> Added laravel socialite vulnerabilities

typo3/cms/2014-05-22-1.yaml, typo3/cms/2014-10-22-1.yaml, typo3/cms/2014-10-22-2.yaml, typo3/cms/2014-12-09-1.yaml, typo3/cms/2014-12-09-2.yaml, typo3/cms/2015-07-01-1.yaml, typo3/cms/2015-07-01-2.yaml, typo3/cms/2015-07-01-3.yaml, typo3/cms/2015-07-01-4.yaml, typo3/cms/2015-07-01-5.yaml, typo3/cms/2015-07-01-6.yaml, typo3/cms/CVE-2014-3941.yaml, typo3/cms/CVE-2014-3943.yaml, typo3/cms/CVE-2014-3944.yaml, typo3/cms/CVE-2014-3946.yaml
Add all the TYPO3 CMS security advisories for 6.2 LTS and 7.x sprint releases, which are available via composer.
=> Add the TYPO3 CMS security advisories for 6.2 and 7.x

namshi/jose/2015-02-19.yaml, validator.php
This issue was fixed in each branch, so we need lower bounds on newer branches. Other 1.1.2 will still be considered as impacted.
=> Fix lower bounds for an advisory

silverstripe/framework/SS-2015-013-1.yaml
I realized that the given date wasn't correct. So I adjusted it to the time of the merge into master:
Date:   Fri May 29 12:53:14 2015 +1200
Merge pull request #4239 from oddnoc/nginx-x-forwarded-host-docs
Add defense against SS-2015-013 to nginx example
--
commit 9efc384582b6397f52f6d8e637550c21f8b5be78
Author: Fred Condo <fcondo@quinn.com>
Date:   Thu May 28 17:00:33 2015 -0700
Add defense against SS-2015-013 to nginx example
=> Fixing date for SS-2015-013

doctrine/doctrine-bundle/2015-08-31.yaml
This advisory was forgotten when creating the advisories for the different Doctrine releases for CVE-2015-5723.
=> Add the advisory for DoctrineBundle

silverstripe/cms/SS-2015-008-1.yaml, validator.php
Although I don't use it, I've spotted that a package seems to have an incorrect Composer name, so I've added a (rather naive) check and corrected it (@spekulatius, could you confirm you meant `silverstripe/cms`?).
This assumes that all Composer packages in this database appear on Packagist (which is currently true, but they don't have to - though would they appear in this database if not?).
I've also noticed that all the SilverStripe advisory URLs are 404s (did they ever work?). Should they be checked too?
=> Validate Composer packages

typo3/flow/2012-03-28.yaml, typo3/flow/CVE-2013-7082.yaml, typo3/neos/2015-03-28.yaml
Since the projects separated earlier this year, the links to the
bulletins are updated to point to the current (and working) ones.
=> Update Neos/Flow advisories

symfony/security-http/CVE-2015-8124.yaml
The split of the Symfony Security component was done with the release of
Symfony 2.4.
=> remove invalid version of symfony/security-http

validator.php
This test adds validation required for the changes in #132
Note: this restricts version constraints accepted in this repository.
Note: will fail on the PR branch (on purpose) with an output like following:
```
codeigniter/framework/2015-10-31-1.yaml
Version constraint "<3.0.3'" is not acceptable.
doctrine/doctrine-bundle/2015-08-31.yaml
Version constraint "<1.5.2'" is not acceptable.
thelia/thelia/2015-04-13-1.yaml
Version constraint ">=2.1.0-beta1" is not acceptable.
zendframework/zendframework1/ZF2010-03.yaml
Version constraint "<1.8.5'" is not acceptable.
```
Once merged into `master`, it shouldn't report any failures.
=> #132 - Improving validator to display violations in constraint strings

simplesamlphp/simplesamlphp/CVE-2016-3124.yaml
This PR adds information for [CVE-2016-3124](https://simplesamlphp.org/security/201603-01) (assigned but pending upload to the CVE database), an information disclosure security issue in `simplesamlphp/simplesamlphp`.
=> Add CVE-2016-3124 (simplesamlphp/simplesamlphp).

simplesamlphp/simplesamlphp/201606-01.yaml
I'm not really sure about the naming of the file.
For the zendframework issues the name given by the advisory naming (e.g. https://github.com/FriendsOfPHP/security-advisories/blob/master/zendframework/zendframework1/ZF2016-02.yaml), so in this case it should be `201606-01` for the simplesamlphp issue. Following the contribute guide it should be `2016-06-08-1`. In case of doctrine only the date of announcement without an increment is used. Any hints?!
=> adds simplesamlphp/simplesamlphp 201606-01: Link injection

drupal/drupal/CVE-2016-5385.yaml, drupal/drupal/CVE-2016-6211.yaml, drupal/drupal/CVE-2016-6212.yaml
Here are the latest two advisories SA-CORE-2016-002, SA-CORE-2016-003 from drupal/drupal included. 
I'm adding only the 8.1.x branch, because 7.x isn't composer supported and 8.0.x didn't receive the fix.
Please have a closer look at it. 
If everything is alright in here, I would add the other ten issues published in SA-CORE-2016-001 which are 8.x-related.
=> adding drupal/drupal with some issues

bugsnag/bugsnag-laravel/CVE-2016-5385.yaml
1.x of the package was not affected because it did not use guzzle.
=> Added bugsnag laravel vulnerability

magento/magento2ce/2016-07-19.yaml
While it saddens me to report a vulnerability that prevents installation of ALL Magento CE versions, that's what happens with 0-day disclosures. I don't agree with what was done with the original disclosure, I'm just here to add it to the database.
The file provided here will have to be updated once the Magento team has released a replacement for the current crypto.
Ref: http://www.openwall.com/lists/oss-security/2016/07/19/3
Copying disclosure text for reference:
```
Date: Tue, 19 Jul 2016 00:56:58 -0400
From: Scott Arciszewski <scott@...agonie.com>
To: fulldisclosure@...lists.org, oss-security@...ts.openwall.com
Subject: Ruining the Magic of Magento's Encryption Library
Hello mcrypt, my old friend
I've come to exploit you again
Because a version slowly rotting
Is well-deserved for a …
```
=> Disallowing installation of current `magento/magento2ce` versions due to 0-day in crypt component

amphp/artax/CVE-2016-5385.yaml
Code has been introduced in https://github.com/amphp/artax/commit/6f8b6c2b#diff-da1906ee835fb5c0e62dc9db19aff36fR27.
`git tag --contains 6f8b6c2b` lists the following tags to ~~be affected~~ contain the above commit:
```
v1.0.0
v1.0.0-alpha
v1.0.0-beta
v1.0.0-beta2
v1.0.0-rc1
v1.0.0-rc2
v1.0.0-rc3
v1.0.0-rc4
v1.0.0-rc5
v1.0.0-rc6
v1.0.1
v1.0.2
v1.0.3
v1.0.4
v2.0.0
v2.0.1
v2.0.2
v2.0.3
v2.0.4
```
I guess `>=1` doesn't cover `v1.0.0-alpha`? What would be the right constraint here?
=> Add CVE-2016-5385 for Artax

drupal/core/CVE-2016-3162.yaml, drupal/core/CVE-2016-3163.yaml, drupal/core/CVE-2016-3164.yaml, drupal/core/CVE-2016-3165.yaml, drupal/core/CVE-2016-3166.yaml, drupal/core/CVE-2016-3167.yaml, drupal/core/CVE-2016-3168.yaml, drupal/core/CVE-2016-3169.yaml, drupal/core/CVE-2016-3170.yaml, drupal/core/CVE-2016-3171.yaml, drupal/core/CVE-2016-5385.yaml, drupal/core/CVE-2016-6211.yaml, drupal/core/CVE-2016-6212.yaml
Following the contribution guide "If some affected code is available through different Composer entries (like when you have read-only subtree splits of a main repository), duplicate the information in several files." I just duplicated the advisories. Should fix #163.
=> duplicating drupal/drupal advisories to drupal/core

simplesamlphp/simplesamlphp/201612-01.yaml
This has already beed added for `simplesamlphp/saml2` in #182 but SimpleSAMLphp itself is also affected.
=> simplesamlphp SSPSA 201612-01: Incorrect signature validation

simplesamlphp/simplesamlphp/201612-02.yaml
This time I'm rather sure that the issue is in simplesamlphp directly and not in a dependency.
The commit with the fix should be: https://github.com/simplesamlphp/simplesamlphp/commit/a2326d75dd14accaac162dd2cb30aaefcc1f9205
Maybe @marcomenzel could verify this before merging?
=> simplesamlphp SSPSA 201612-02: Incorrect signature validation

typo3/cms/2016-11-22-1.yaml, typo3/cms/2016-11-22-2.yaml
fixing mistakes made in d01ca7e9299e18eb7ca4c551a4ea491340af3b99
should be self-explanatory :angel:
=> fix typo3/cms branches/version for two advisories

magento/magento1ce/2017-02-07.yaml, magento/magento1ee/2017-02-07.yaml
This vulnerability exists in the underlying Zend 1.x library. The
upstream Zend library has hit EOL, however Magento maintains a fork of
the library with security fixes as they migrate to Zend 2.x (in Magento
2)
This vulnerability exists in code in both the CE and EE version
Fixes #202
=> Add the SUPEE-9652 RCE in Magento 1.x CE/EE

drupal/core/CVE-2016-9449.yaml, drupal/core/CVE-2016-9450.yaml, drupal/core/CVE-2016-9452.yaml, drupal/drupal/CVE-2016-9449.yaml, drupal/drupal/CVE-2016-9450.yaml, drupal/drupal/CVE-2016-9452.yaml
the `branches` used for SA-CORE-2016-005 aren't correct.
This pr will fix them.
=> fixing drupal advisory constraints

illuminate/auth/2014-04-15.yaml, illuminate/database/2014-05-20.yaml
- Use https
- Use 5.1 docs because upgrade guides for 4.* were removed in 5.2 docs
=> Fix illuminate/* links

onelogin/php-saml/2016-10-04.yaml, onelogin/php-saml/2017-02-28.yaml
Based on the warnings in the README file of the library, I added these 2 security related matters. I am not sure if the CVE mentioned in the README should be added. I can't find the CVE in the official CVE database.
https://github.com/onelogin/php-saml/blob/master/README.md
=> add onelogin/php-saml security issues

simplesamlphp/simplesamlphp/201709-01.yaml
Like @stof mentioned in https://github.com/FriendsOfPHP/security-advisories/pull/225/files#r137498654 I added 1.12.x and 1.13.x which are affected by SSPSA 201709-01 and distributed by composer/packagist.
=> add simplesamlphp/simplesamlphp SSPSA 201709-01

ezsystems/ezpublish-legacy/2017-09-11-1.yaml
Ref: http://share.ez.no/community-project/security-advisories/ezsa-2017-006-information-disclosure-in-backend-content-tree-menu
=> EZSA-2017-006: Information disclosure in backend content tree menu

cartalyst/sentry/2016-09-05.yaml
This issue didn't get fixed until 2.1.7
See also [This comment](https://github.com/cartalyst/sentry/pull/545#issuecomment-346587360)
=> Specify Sentry version

gree/jose/2016-08-30.yaml
The fix against algorithm spoofing has been added to version 2.2.1:
https://github.com/nov/jose-php/blob/master/src/JOSE/JWS.php#L131
=> Add the advisory for the gree/jose vulnerability

phpxmlrpc/extras/2017-10-29.yaml
it seems that the version was wrong according to https://github.com/gggeek/phpxmlrpc-extras/releases/tag/0.6.1 linked in the file.
=> fixed typo in version of phpxmlrpc.

simplesamlphp/saml2/CVE-2018-6519.yaml, simplesamlphp/simplesamlphp/CVE-2017-18121.yaml, simplesamlphp/simplesamlphp/CVE-2017-18122.yaml, simplesamlphp/simplesamlphp/CVE-2018-6520.yaml, simplesamlphp/simplesamlphp/CVE-2018-6521.yaml
We've got CVE IDs for the 5 advisories missing them in SimpleSAMLphp. Here are they.
=> Add CVE IDs to several advisories

yiisoft/yii2-dev/CVE-2015-5467.yaml, yiisoft/yii2-dev/CVE-2018-6009.yaml, yiisoft/yii2-dev/CVE-2018-6010.yaml, yiisoft/yii2/CVE-2018-6009.yaml, yiisoft/yii2/CVE-2018-6010.yaml
These are fixed with todays release of Yii 2.0.14.
http://www.yiiframework.com/news/165/yii-2-0-14-is-released/
See "Security" headline for details.
Both issues affect packages `yiisoft/yii2` and `yiisoft/yii2-dev` so the files are duplicated for these.
Also copied a missing CVE-2015-5467 from `yiisoft/yii2` to `yiisoft/yii2-dev`.
=> added Yii Framework CVE-2018-6009 and CVE-2018-6010

README.md, validator.php
Alternative to #242. I don't think we need the `unfixed` entry. Having a `time` set as `null` is semantically enough.
/cc @paragonie-scott @stof
=> Allow time to be null when the issue is not fixed yet

erusev/parsedown/2017-05-01.yaml
Parsedown has had multiple XSS issues for a long time when using its `->setMarkupEscaped(true)` option (e.g. being able to break out of the AST representation by adding quotes in link ~~addresses~~ titles). All of these issues are fixed in https://github.com/erusev/parsedown/pull/495, but this has remained open for almost a year now, and there appears to be no interest in merging it any time soon from the repository owner (I digress).
There might be some debate as to whether XSS issues in a markdown parser can actually be considered security issues (since markdown itself permits HTML). To address this I would present the following:
* The Parsedown Wiki has for a long time [stated](https://github.com/erusev/parsedown/wiki/Tutorial:-Get-Started/f9d881da38d8ef737ffc0c0a140b124ba3367904) that …
=> Add advisory for Parsedown

paragonie/random_compat/2016-03-16.yaml
https://github.com/paragonie/random_compat/issues/96
TL;DR - In environments where the PHP process is forked, `openssl_random_psuedo_bytes` can generate the same stream of values.
There are other security issues that also caused @paragonie-scott concern. 
Also I'm not sure what to do with the branch name, the vulnerability spans more than one branch and can best be described as "all versions 1.*? (edit - as @stof mentioned it's actually all versions <2 )
=> paragonie/random_compat 1.* uses insecure CSPRNG (openssl_random_pseudo_bytes())

erusev/parsedown/2017-05-01.yaml
As requested in https://github.com/FriendsOfPHP/security-advisories/pull/257#issuecomment-369240396
=> erusev/parsedown 1.7.0 addresses advisory #257

pagarme/pagarme-php/2017-11-20.yaml
Looking at the code I see that the security issue about
[pagarme/pagarme-php](https://github.com/pagarme/pagarme-php) reported
in #241 only appears on versions below 3.x. Since the stable version (on
branch V3) doesn't have the vulnerability this PR aims to fix the
version range.
=> Adjust report version range

drupal/drupal/CVE-2017-6926.yaml, drupal/drupal/CVE-2017-6927.yaml, drupal/drupal/CVE-2017-6928.yaml, drupal/drupal/CVE-2017-6929.yaml, drupal/drupal/CVE-2017-6930.yaml, drupal/drupal/CVE-2017-6931.yaml, drupal/drupal/CVE-2017-6932.yaml
Forgot "drupla/drupal" in the previous pull request.
CVE-2017-6926
CVE-2017-6927
CVE-2017-6928
CVE-2017-6929
CVE-2017-6930
CVE-2017-6931
CVE-2017-6932
=> Drupal advisory SA-CORE-2018-001 (for drupla/drupal module)

squizlabs/php_codesniffer/2017-03-01.yaml
The date/time of the issue was in an incorrect format (`2017-01-03` vs `2017-03-01`).
As I was fixing this anyway, I checked the actual time of the commit fixing this which can be seen as the first public announcement of the vulnerability.
So the new time is based on when the fix was originally committed to PHPCS: https://github.com/squizlabs/PHP_CodeSniffer/commit/029305e754dde022c4c8ee48d392c16b61fffe2a
=> Fix `time` in advisory for squizlabs/php_codesniffer < 2.8.1

squizlabs/php_codesniffer/2017-05-18.yaml
See: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.1
~~Time based on when the fix was originally pulled to PHPCS: https://github.com/squizlabs/PHP_CodeSniffer/pull/1475~~
Updated to reflect the time when the fix was originally *merged* into PHPCS: https://github.com/squizlabs/PHP_CodeSniffer/commit/7ce7bb942f5667724e81a3ea99e805a30be6c05b
=> Add advisory for squizlabs/php_codesniffer 3.0.0

drupal/core/CVE-2018-7600.yaml, drupal/drupal/CVE-2018-7600.yaml
https://www.drupal.org/sa-core-2018-002
Mirrored patches:
Drupal 6: https://gist.github.com/paragonie-scott/dca4690a504a1d860575041eb274eeef
Drupal 7: https://gist.github.com/paragonie-scott/79ddffd734bf15a9d86b723d74d15572
Drupal 8: https://gist.github.com/paragonie-scott/ee034dc43cbaafb9ff1cfcdda77d3240
The actual mitigation of these patches: https://gist.github.com/paragonie-scott/79ddffd734bf15a9d86b723d74d15572#file-drupal-7-x-2018-002-patch-L91
Explanation: https://twitter.com/codeincarnate/status/979080318966730753
> Drupal uses the hash "#" at the beginning of array keys to signify special keys usually that lead to some type of computation. Basically you can inject these. See Drupal form API for example
=> Drupal SA-CORE-2018-002

illuminate/auth/CVE-2017-9303.yaml, laravel/framework/CVE-2017-9303.yaml
- Listed in the CVE database under [CVE-20170-9303](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9303). 
- Documented at [Laravel 5.4 releases](https://laravel.com/docs/5.4/releases#laravel-5.4.22). 
- Fixed with commit [#cef1055](https://github.com/laravel/framework/commit/cef10551820530632a86fa6f1306fee95c5cac43).
=> CVE-2017-9303 for laravel auth

illuminate/auth/CVE-2017-14775.yaml, laravel/framework/CVE-2017-14775.yaml
- Listed in the CVE database under [CVE-20170-14775](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-14775). 
- Documented (and fixed) at [Laravel PR#21320](https://github.com/laravel/framework/pull/21320).
=> CVE-2017-14775 for laravel auth

paypal/merchant-sdk-php/CVE-2017-6099.yaml, slim/slim/CVE-2015-2171.yaml
- CVE-2017-6099 <https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-6099>.
- CVE-2015-2171 <https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-2171>.
paypal/merchant-sdk-php:
Cross-site scripting (XSS) vulnerability in GetAuthDetails.html.php in PayPal PHP Merchant SDK (aka merchant-sdk-php) 3.9.1 allows remote attackers to inject arbitrary web script or HTML via the token parameter.
slim/slim:
Middleware/SessionCookie.php in Slim before 2.6.0 allows remote attackers to conduct PHP object injection attacks and execute arbitrary PHP code via crafted session data.
=> Paypal and Slim.

paypal/merchant-sdk-php/CVE-2017-6099.yaml
Instead of referencing the affected version tag it's probably better to link to the real issue description.
ping @ularanigu
=> replace advisory link with actual issue URL

erusev/parsedown/2017-05-01.yaml
A [CVE](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-1000162) was assigned for this issue.
=> Add CVE for Parsedown vulnerability

cakephp/cakephp/2018-05-20.yaml
We had a cross site scripting flaw in some of our development mode error pages.
=> Add new issue in CakePHP

typo3/cms-core/2018-07-12-1.yaml, typo3/cms-core/2018-07-12-2.yaml, typo3/cms-core/2018-07-12-3.yaml, typo3/cms-core/2018-07-12-4.yaml, typo3/cms/2018-07-12-1.yaml, typo3/cms/2018-07-12-2.yaml, typo3/cms/2018-07-12-3.yaml, typo3/cms/2018-07-12-4.yaml
* https://typo3.org/security/advisory/typo3-core-sa-2018-001/
* https://typo3.org/security/advisory/typo3-core-sa-2018-002/
* https://typo3.org/security/advisory/typo3-core-sa-2018-003/
* https://typo3.org/security/advisory/typo3-core-sa-2018-004/
Package "typo3/cms" addresses legacy packages, "typo3/cms-core"
addresses the sub-tree split packages since v8.x, which became
a mandatory package in v9.0.0.
=> [TASK] Add TYPO3-CORE-SA-2018-001 to TYPO3-CORE-SA-2018-004

illuminate/cookie/2018-08-08-1.yaml, laravel/framework/2018-08-08-1.yaml
As mentioned in the [official docs](https://laravel.com/docs/5.6/upgrade#upgrade-5.6.30) and [Laravel News](https://laravel-news.com/laravel-5-6-30). The merged pull request containing the fix for `5.6.x` branch is [over here](https://github.com/laravel/framework/pull/25121). And the commit for the `5.5.x` branch is either [this one](https://github.com/laravel/framework/commit/c5dc9c870a8a1af6c7e827dd81bd15f0a1561cc4), the [parent of that one](https://github.com/laravel/framework/commit/6df8767c657b5b14bb8ac23b4858f9f8def0cb3c) or the [parent-of-the-parent](https://github.com/laravel/framework/commit/3716d145b60150c1f86c25b4004390a23d8328ea).
=> Add advisory for Laravel cookie serialization vulnerability

zendframework/zendframework/ZF2018-01.yaml
As zendframework/zendframework 2.4 contains the #314 vulnerability as well.
=> Add a reference to #314 for zendframework/zendframework

openid/php-openid/CVE-2013-4701.yaml
Note that I explicitly didn't include CVE-2016-2049, which is still unfixed (https://github.com/openid/php-openid/issues/128).
=> Add CVE for openid/php-openid

alterphp/easyadmin-extension-bundle/2018-10-02.yaml
As mentioned here: https://github.com/alterphp/EasyAdminExtensionBundle/commit/68407ca5be644d1c53fb894453df951230afc6dc
=> Add easy-admin extension bundle security flaw

fooman/tcpdf/CVE-2018-17057.yaml, fossar/tcpdf-parser/CVE-2018-17057.yaml, la-haute-societe/tcpdf/CVE-2018-17057.yaml, spoonity/tcpdf/CVE-2018-17057.yaml, tecnickcom/tcpdf/CVE-2018-17057.yaml, wallabag/tcpdf/CVE-2018-17057.yaml
`fooman/tcpdf` is a fork of `tecnickcom/tcpdf`
Both are affected by CVE-2018-17057.
=> CVE-2018-17057

ezsystems/ezpublish-legacy/2018-10-31-1.yaml
Update for http://share.ez.no/community-project/security-advisories/ezsa-2018-005-passwordless-login-for-ldap-users
=> ezpublish-legacy EZSA-2018-005

ezsystems/ezpublish-legacy/2018-11-01-1.yaml
http://share.ez.no/community-project/security-advisories/ezsa-2018-006-xss-vulnerability-in-disabled-module-error-template
=> ezpublish-legacy EZSA-2018-006

symfony/security/CVE-2016-2403.yaml, symfony/security/CVE-2016-4423.yaml, symfony/security/CVE-2017-16652.yaml, symfony/security/CVE-2017-16653.yaml, symfony/security/CVE-2018-19790.yaml
While reviewing #342 I realised that we missed to include some CVEs associated with some of the Security subcomponents where not included in `symfony/security`.
=> sync CVEs into symfony/security

typo3/cms-core/2018-12-11-1.yaml, typo3/cms-core/2018-12-11-2.yaml, typo3/cms-core/2018-12-11-3.yaml, typo3/cms-core/2018-12-11-4.yaml, typo3/cms-core/2018-12-11-5.yaml, typo3/cms-core/2018-12-11-6.yaml, typo3/cms-core/2018-12-11-7.yaml, typo3/cms-core/2018-12-11-8.yaml, typo3/cms/2018-12-11-1.yaml, typo3/cms/2018-12-11-2.yaml, typo3/cms/2018-12-11-3.yaml, typo3/cms/2018-12-11-4.yaml, typo3/cms/2018-12-11-5.yaml, typo3/cms/2018-12-11-6.yaml, typo3/cms/2018-12-11-7.yaml, typo3/cms/2018-12-11-8.yaml
Add latest TYPO3 CMS Security Advisories
* https://typo3.org/security/advisory/typo3-core-sa-2018-005/
* https://typo3.org/security/advisory/typo3-core-sa-2018-006/
* https://typo3.org/security/advisory/typo3-core-sa-2018-007/
* https://typo3.org/security/advisory/typo3-core-sa-2018-008/
* https://typo3.org/security/advisory/typo3-core-sa-2018-009/
* https://typo3.org/security/advisory/typo3-core-sa-2018-010/
* https://typo3.org/security/advisory/typo3-core-sa-2018-011/
* https://typo3.org/security/advisory/typo3-core-sa-2018-012/
Package "typo3/cms" addresses legacy packages, "typo3/cms-core"
addresses the sub-tree split packages since v8.x, which became
a mandatory package in v9.0.0.
=> [FEATURE] Add TYPO3-CORE-SA-2018-005 to TYPO3-CORE-SA-2018-012

league/commonmark/2018-12-29.yaml
[A vulnerability found in league/commonmark 0.15.6 - 0.18.0](https://github.com/thephpleague/commonmark/issues/337) has been fixed in [0.18.1](https://github.com/thephpleague/commonmark/releases/tag/0.18.1).
=> Add XSS vulnerability in league/commonmark

league/commonmark/CVE-2018-20583.yaml
Apologies for not including this in #350 - we didn't receive our CVE ID until this morning.
=> Add assigned CVE ID to league/commonmark vulnerability

api-platform/core/2019-01-15.yaml
=> api-platform/core: Access control bypass in the GraphQL mutations

.editorconfig
To prevent IDEs from defaulting to two spaces for indentation
=> Add editorconfig with 4 spaces for indentation

drupal/core/CVE-2019-6338.yaml, drupal/core/CVE-2019-6339.yaml, drupal/drupal/CVE-2019-6338.yaml, drupal/drupal/CVE-2019-6339.yaml
Just noticed that the year was wrong on the last Drupal CVE files. Probably does not matter that much, and very quick to do so, right after new years :)
Anyway, here is a PR fixing that up.
=> Fix date for CVE-2019-6338 and CVE-2019-6339

simplesamlphp/simplesamlphp/2018-12-20.yaml
Per the linked advisory, this is only applicable to 1.16.x. Adding a minimum constraint.
=> Update version constraint on simplesamlphp/simplesamlphp/2018-12-20.yaml

typo3/cms-core/2019-05-07-1.yaml, typo3/cms-core/2019-05-07-2.yaml, typo3/cms-core/2019-05-07-3.yaml, typo3/cms-core/2019-05-07-4.yaml, typo3/cms-core/2019-05-07-5.yaml, typo3/cms/2019-05-07-1.yaml, typo3/cms/2019-05-07-2.yaml, typo3/cms/2019-05-07-3.yaml, typo3/cms/2019-05-07-4.yaml, typo3/cms/2019-05-07-5.yaml
+ autogenerated by https://github.com/TYPO3/darth
+ `bin/darth security 8.7.25,9.5.6`
=> [TASK] Add security advisories for TYPO3's May 2019 releases

sylius/grid-bundle/CVE-2019-12186.yaml, sylius/grid/CVE-2019-12186.yaml, sylius/sylius/CVE-2019-12186.yaml
Three packages affected:
`sylius/sylius` used to replace `sylius/grid` and `sylius/grid-bundle`
`sylius/grid-bundle` used to be standalone, now also replaces `sylius/grid`
=> Sylius, CVE-2019-12186: XSS injection in the Grid component

README.md
Since (at least for me) the validator exceeds PHP's [default memory limit of 128MB](https://www.php.net/manual/en/ini.core.php#ini.sect.resource-limits) when running the validator locally (seems to require about 150MB).
This note might have saved me a couple mins while I thought I somehow caused the validator to break :)
=> Remove memory limit in validator usage example

drupal/core/CVE-2019-6342.yaml, drupal/drupal/CVE-2019-6342.yaml
Just a single version (`8.7.4`) is affected, but I have to define a range with an upper boundary (defined with `<`). More: https://github.com/FriendsOfPHP/security-advisories/issues/408
=> add Drupal core - Critical - Access bypass - SA-CORE-2019-008

contao/newsletter-bundle/CVE-2018-5478.yaml
The file was actually a duplicate of https://github.com/FriendsOfPHP/security-advisories/blob/master/contao/core/CVE-2018-5478.yaml with wrong information in it.
=> Delete a wrong file

robrichards/xmlseclibs/CVE-2019-3465.yaml
The security advisory regarding this issue is published in the given URL.
=> Add link to security advisory

validator.php
It does not make sense to have multiple upper bounds for a range, as they would need to match all, meaning that the lowest version of them would be the useful one. Same is true for lower bounds (except that the highest version is the meaningful one).
Defining multiple affected ranges is what branches are representing in the advisory format.
Build will be green once #425 is merged
=> Add a validator ensuring that each branch has a well-formed range

scheb/two-factor-bundle/2018-07-08.yaml, scheb/two-factor-bundle/2019-12-19.yaml
Addding security advisories for `scheb/two-factor-bundle`. One recent one and an older one (but I still see people using that version).
=> Add security advisories for scheb/two-factor-bundle

drupal/core/2019-12-18-1.yaml, drupal/core/2019-12-18-2.yaml, drupal/core/2019-12-18-3.yaml, drupal/core/2019-12-18-4.yaml, drupal/drupal/2019-12-18-1.yaml, drupal/drupal/2019-12-18-2.yaml, drupal/drupal/2019-12-18-3.yaml, drupal/drupal/2019-12-18-4.yaml
I am not rreally sure about what to do about these descriptions:
> Versions of Drupal 8 prior to 8.7.x are end-of-life and do not receive security coverage.
Should we mark the 7.x and the <8.7.0 as effected or not? Even if we don't know if there is vulnerable code?
=> Drupal core - Multiple vulnerabilities

scheb/two-factor-bundle/2018-07-08.yaml
Adding the missing lower version constraint for the one issue of `scheb/two-factor-bundle`.
=> Add lower version constraint

drupal/core/2019-12-18-1.yaml
The [sa-core-2019-009 ](https://www.drupal.org/sa-core-2019-009)advisory does not affect Drupal versions < 8.
=> Correct vulnerable versions of Drupal

sylius/resource-bundle/CVE-2020-5220.yaml, sylius/sylius/CVE-2020-5220.yaml
Added entries for `sylius/sylius` (as it used to replace `sylius/resource-bundle`) and also for `sylius/resource-bundle`.
=> Sylius/ResourceBundle, CVE-2020-5220: Ability to define unintended serialisation groups via HTTP header which might lead to data exposure

oneup/uploader-bundle/CVE-2020-5237.yaml
For more information see https://github.com/1up-lab/OneupUploaderBundle/security/advisories/GHSA-x8wj-6m73-gfqp.
=> Add CVE-2020-5237: Relative Path Traversal (CWE-23) in chunked uploads

oneup/uploader-bundle/CVE-2020-5237.yaml
Sorry to bother you again - I've noticed a little typo as version `2.0.0` is also vulnerable.
=> Fix version constraint

phpoffice/phpexcel/CVE-2018-19277.yaml
The PHP Excel project released another version which basically archived the project but importantly didn't fix this vulnerability.
Changes in the 1.8.2 release: https://github.com/PHPOffice/PHPExcel/compare/1.8.2...1.8
=> Corrects the vulnerable version of PHP Excel

silverstripe/assets/CVE-2019-12245.yaml
We just noticed we made a mistake when defining which versions are vulnerable.
The vulnerability got fixed in 1.3.5, but version 1.4.0, 1.4.1, 1.4.2 and 1.4.3 are also vulnerable. This PR update the branch list to reflect that.
I also double checked that 1.5.0 isn't vulnerable.
The [public disclosure](https://www.silverstripe.org/download/security-releases/cve-2019-12245) has also been updated to say that you need to upgrade to 1.4.4.
=> Fix mismatched vulnerable version for CVE-2019-12245

phpunit/phpunit/CVE-2017-9841.yaml
The previous link to vulnbusters.com no longer functions and may be attempting to trick user into downloading malicious software. I replaced it with a link to nvd.nist.gov. This seemed like a good alternative link.
=> Replaced broken link

amphp/http-client/2020-06-16.yaml
The branch name is currently `master` but will change to `4.x` once there's a v5.x. Not sure whether the branch name is important or whether just the versions matter.
=> Add https://github.com/amphp/http-client/releases/tag/v4.4.0

silverstripe/framework/CVE-2019-19326.yaml, silverstripe/framework/CVE-2020-6164.yaml, silverstripe/framework/CVE-2020-9311.yaml, silverstripe/graphql/CVE-2020-6165.yaml
We released Silverstripe CMS 4.6.0 and related patch releases this week. We disclosed a few security issues with those releases.
=> Add entries for issues fixed by Silverstripe CMS 4.6.0 release

illuminate/database/2020-08-06.yaml, laravel/framework/2020-08-06-1.yaml
See https://blog.laravel.com/security-release-laravel-61834-7232.
I'm not sure if the 5.x branch should be marked as unfixed... :thinking: 
Also: should there be an additional entry for the `illuminate/database` package?
=> Add Laravel vuln in eloquent models

illuminate/cookie/2020-07-27-1.yaml, laravel/framework/2020-07-27-1.yaml
See https://blog.laravel.com/laravel-cookie-security-releases.
I'm not sure if the 5.x branch should be marked as unfixed... :thinking: 
Also: should there be an additional entry for the `illuminate/cookie` package?
=> Add Laravel vuln in cookie session driver

livewire/livewire/2020-09-22-1.yaml
Notes a validation issue introduced in Livewire 2.2.5 (and then fixed in 2.2.6) whereby the `Component::validate()` method returns all property data instead of just the validated properties as it previously had. This regression could potentially cause security issues if the return value was used with unguarded models or other scenarios, if the other property names lined up.
https://github.com/livewire/livewire/releases/tag/v2.2.6
=> Add Livewire 2.2.5 validation advisory

typo3fluid/fluid/2019-05-07-1.yaml
Vulnerabilities have been fixed and announced already in May 2019.
Corresponding tracking of the particular library `typo3fluid/fluid`
was missing in this database.
see https://typo3.org/security/advisory/typo3-core-sa-2019-013
=> [TASK] Add TYPO3 Fluid security advisory from May 2019

mediawiki/core/CVE-2020-10959.yaml, mediawiki/core/CVE-2020-10960.yaml, mediawiki/core/CVE-2020-25812.yaml, mediawiki/core/CVE-2020-25813.yaml, mediawiki/core/CVE-2020-25814.yaml, mediawiki/core/CVE-2020-25815.yaml, mediawiki/core/CVE-2020-25827.yaml, mediawiki/core/CVE-2020-25828.yaml
I am not entirely sure about the constraint for vulnerabilities that only affect the RC versions of 1.35 :slightly_frowning_face:
=> Add 2020 CVEs for MediaWiki

phpmyadmin/phpmyadmin/CVE-2020-10802.yaml, phpmyadmin/phpmyadmin/CVE-2020-10803.yaml, phpmyadmin/phpmyadmin/CVE-2020-10804.yaml, phpmyadmin/phpmyadmin/CVE-2020-26934.yaml, phpmyadmin/phpmyadmin/CVE-2020-26935.yaml, phpmyadmin/phpmyadmin/CVE-2020-5504.yaml
Similar to https://github.com/FriendsOfPHP/security-advisories/pull/502#discussion_r527120521, I could not always find the first vulnerable version.
=> Add 2020 CVEs for phpmyadmin

drupal/core/CVE-2018-9861.yaml, drupal/core/CVE-2019-10909.yaml, drupal/drupal/CVE-2018-9861.yaml, drupal/drupal/CVE-2019-10909.yaml
Quick note, the 2019 Drupal advisory lists three separate CVEs. Both the 2018 and 2019 advisories are caused by underlying libraries used by Drupal: for 2018, CKEditor, for 2019, Symfony. If you look at the CVE data, Drupal is listed as a vulnerable configuration, but only for one of the 2019 CVEs:
* https://nvd.nist.gov/vuln/detail/CVE-2018-9861
* https://nvd.nist.gov/vuln/detail/CVE-2019-10909
* https://nvd.nist.gov/vuln/detail/CVE-2019-10910
* https://nvd.nist.gov/vuln/detail/CVE-2019-10911
It might be worth reaching out to the maintainers of the NIST NVD to add Drupal as a vulnerable configuration on the last two CVEs listed above.
=> Add assigned CVEs to Drupal advisories

phpoffice/phpspreadsheet/CVE-2020-7776.yaml
Fix CVE-2020-7776 identifier (CVE-2019-7776 -> CVE-2020-7776)
phpoffice/phpspreadsheet
=> Fix CVE-2020-7776 identifier

illuminate/database/2021-01-14.yaml
Related to 9dfa6c8280dcb65776e235d064d9463aeef8daad
See https://github.com/FriendsOfPHP/security-advisories/pull/520#issuecomment-760831320.
=> Add advisory for illuminate/database

pear/archive_tar/CVE-2020-36193.yaml
CVE-2020-36193 
Archive_Tar through 1.4.11 allows write operations with Directory Traversal due to inadequate checking of symbolic links (a related issue to CVE-2020-28948)
=> Create CVE-2020-36193.yaml (#1)

illuminate/database/2021-01-21.yaml, laravel/framework/2021-01-21.yaml
The previous fix (CVE-2021-21263) could be bypassed,
so new versions were released.
Source:
* https://github.com/laravel/framework/pull/35865#discussion_r561578503
* https://github.com/laravel/framework/pull/35972
Closes #528.
=> Add new Laravel database advisory

illuminate/database/2021-01-21.yaml, laravel/framework/2021-01-21.yaml
See aa3112393c8a76b4e7b6613ed0a4a89494c63552 from https://github.com/FriendsOfPHP/security-advisories/pull/532#issuecomment-771662648.
cc @naderman
=> Update Laravel security advisory

README.md
Use `--dir` option for symfony security:check otherwise it will fail:
```bash
Incorrect usage: Too many arguments
```
=> Use --dir option for symfony security:check

facade/ignition/CVE-2021-3129.yaml
This PR adds a record for the facade/ignition RCE vulnerability.
- https://www.ambionics.io/blog/laravel-debug-rce
- https://github.com/facade/ignition/pull/334
- https://github.com/facade/ignition/pull/353
=> Adds Record For facade/ignition RCE: CVE-2021-3129

facade/ignition/CVE-2021-3129.yaml
See:
https://github.com/FriendsOfPHP/security-advisories/pull/545#discussion_r602150214
* constraints reversed, having minimum version first
* Changed max version constraint to `<`
* updated timestamp to match the fix PR time for 2.4.x
=> Cleanup facade/ignition entry

doctrine/orm/2021-04-06.yaml
This is technically a bugfix on our end, but I want to burn the release as a security problem anyways, because it can have follow up security implications for users.
=> Doctrine ORM QueryBuilder regression in 2.8.3 can have security implications

phpseclib/phpseclib/CVE-2021-30130.yaml
phpseclib before 2.0.31 and 3.x before 3.0.7 mishandles RSA PKCS#1 v1.5 signature verification.
**References**
- https://nvd.nist.gov/vuln/detail/CVE-2021-30130
- phpseclib/phpseclib#1635
- https://github.com/phpseclib/phpseclib/releases/tag/2.0.31
- https://github.com/phpseclib/phpseclib/releases/tag/3.0.7
=> phpseclib CVE-2021-30130

validator.php
This does the same thing but with a slighty easier to read syntax:
* `(\\<|\\>)` can be simplified as `([<>])`.
* `{0,1}` can be simplified as `?`.
* Escaping `.` is not required in `[]`.
* Escaping `-`  is not required outside `[]`.
=> Simplify regexp

neos/flow/2012-03-28.yaml, neos/flow/2015-11-23.yaml, neos/flow/2016-11-01.yaml, neos/flow/2017-04-12.yaml, neos/flow/CVE-2013-7082.yaml, neos/neos/2015-03-28.yaml, neos/neos/2015-11-23.yaml, neos/neos/2019-06-17.yaml, neos/swiftmailer/2017-01-06.yaml
This adds advisories for neos/* under the neos vendor name, those
packages replace the ones from typo3/*.
=> Add neos/* advisories

rmccue/requests/CVE-2021-29476.yaml
See:
* https://github.com/WordPress/Requests/releases/tag/v1.8.0
* https://github.com/WordPress/Requests/security/advisories/GHSA-52qp-jpq7-6c54
=> Add advisory for rmccue/requests 1.6.0 < 1.8.0

symfony/security/CVE-2020-5275.yaml, symfony/security/CVE-2021-21424.yaml
There are no version after 4.x for the symfony/security component
=> Fix non-existant version for symfony/security

wp-cli/wp-cli/CVE-2021-29504.yaml
Only after the change in #567 was merged  I noticed that I had copied the title from the upstream vulnerability, instead of the one that was fixed directly in the `wp-cli/wp-cli` package.
This PR fixes the title to match the GitHub adivsory.
=> Fix title in wp-cli/wp-cli CVE-2021-29504

silverstripe/framework/CVE-2020-26138.yaml, silverstripe/framework/CVE-2021-25817.yaml, silverstripe/graphql/CVE-2020-26136.yaml
We released Silverstripe CMS 4.8.0 and related patch releases this week. We disclosed a few security issues with those releases.
=> Add entires for issues fixed by Silverstripe CMS 4.8.0 release

codeception/codeception/CVE-2021-23420.yaml
See:
* https://github.com/advisories/GHSA-4574-qv3w-fcmg
* https://nvd.nist.gov/vuln/detail/CVE-2021-23420
Again, this is untested, as I still haven't found a way to test these with a local repository
=> Add CVE-2021-23420 in codeception/codeception

lcobucci/jwt/CVE-2021-41106.yaml
According to published Github security issue
Done via Github web interface, no checks have been run on my side.
=> Add CVE-2021-41106 for lcobucci/jwt

phpoffice/phpexcel/CVE-2018-19277.yaml
According advisory postings, this doesn't impact v1.8.0 or higher: https://github.com/advisories/GHSA-vvwv-h69m-wg6f & https://nvd.nist.gov/vuln/detail/CVE-2019-12331
=> fix(CVE-2018-19277): adjust affected range

matyhtf/framework/CVE-2021-43676.yaml
See https://github.com/advisories/GHSA-mh9j-v6mq-pfch.
There is no fix yet so we might have to update the YAML later.
=> Add CVE-2021-43676

dompdf/dompdf/CVE-2022-28368.yaml
Creating this manually kind of sucks.
Can we somehow import all Github security advisories like https://github.com/advisories/GHSA-x752-qjv4-c4hc for PHP composer projects automatically? https://github.com/advisories?query=type%3Areviewed+ecosystem%3Acomposer
=> Add CVE-2022-28368 for Dompdf

validator.php
The validator accepts `master`. With the new git default being `main`, I think we should accept it (see #633 for a usage of it).
What do you think @fabpot @naderman ?
=> Accept main as a branch name

drupal/core/CVE-2022-25275.yaml, drupal/core/CVE-2022-25277.yaml
https://www.drupal.org/sa-core-2022-014
I see that a lot of security advisories were missing, but I just added the most recent. Also marked the last 8.9 branch + 9.0/9.1/9.2 as insecure because they are no longer covered in the security process. Combined with https://github.com/FriendsOfPHP/security-advisories/blob/master/drupal/core/CVE-2021-33829.yaml that should only keep 9.3.19 and 9.4.3 als secure options.
=> Drupal core - Critical - Arbitrary PHP code execution - SA-CORE-2022-014

in2code/femanager/CVE-2022-44543.yaml
The extension maintainer released an additional version for websites running TYPO3 ELTS
=> Update advisory for CVE-2022-44543 in in2code/femanager

silverstripe/subsites/CVE-2022-42949.yaml
Add notice for [CVE-2022-42949](https://www.silverstripe.org/download/security-releases/cve-2022-42949) on silverstripe/subsites
=> Add CVE-2022-42949 for silverstripe/subsites

firebase/php-jwt/CVE-2021-46743.yaml
This vulnerability is a bit older, but it seems to be missing in this database.
=> Document firebase/php-jwt CVE-2021-46743

phpseclib/phpseclib/CVE-2023-27560.yaml
One more missing CVE which I was able to catch, not sure how many are not in this repo.
I'm in doubts if symfony's security checker is safe to use with production-ready apps, since looks like everyone migrates to use github's advisories. IMO this repository should be abandoned in favor of https://github.com/advisories/ and so security checker.
Edit: meanwhile I'm migrating to `composer audit`
=> CVE-2023-27560

laravel/fortify/CVE-2022-25838.yaml
This vulnerability is a bit older, but it seems to be missing in this database.
=> laravel/fortify CVE-2022-25838

dompdf/dompdf/CVE-2023-23924.yaml
This vulnerability is a bit older, but it seems to be missing in this database.
=> dompdf/dompdf CVE-2023-23924

silverstripe/graphql/CVE-2023-28104.yaml
Originally had versions as `['4.1.1']` and `['4.2.2']` as only those exact versions are affected - but validation requires me to use `['>=a.b.c', '<x.y.z']` syntax.
=> Add CVE-2023-28104 for silverstripe/graphql

silverstripe/admin/SS-2023-001.yaml, silverstripe/framework/CVE-2023-22728.yaml, silverstripe/framework/CVE-2023-22729.yaml
I can do these in separate PRs if you prefer, but I didn't see anything about that in the README so I assume this is okay.
=> Add security advisories for Silverstripe CMS 4.13.0

silverstripe/admin/SS-2023-002.yaml, silverstripe/framework/CVE-2023-32302.yaml
Adding two recently patched advisories for Silverstripe CMS.
=> Add Silverstripe CMS advisories SS-2023-002 and CVE-2023-32302

phpseclib/phpseclib/CVE-2023-49316.yaml
`composer audit` found more security vulnerability advisory than the local checker. This is to add CVE-2023-49316 to this repository.
Since this is my first contribution to this repository, I copied [CVE-2023-27560.yaml](https://github.com/FriendsOfPHP/security-advisories/blob/master/phpseclib/phpseclib/CVE-2023-27560.yaml) and hope that I did all the necessary changes.
=> CVE-2023-49316

silverstripe/admin/CVE-2023-49783.yaml, silverstripe/framework/CVE-2023-48714.yaml, silverstripe/graphql/CVE-2023-44401.yaml
- https://www.silverstripe.org/download/security-releases/cve-2023-49783/
- https://github.com/silverstripe/silverstripe-admin/security/advisories/GHSA-j3m6-gvm8-mhvw
- https://www.silverstripe.org/download/security-releases/cve-2023-48714/
- https://github.com/silverstripe/silverstripe-framework/security/advisories/GHSA-qm2j-qvq3-j29v
- https://www.silverstripe.org/download/security-releases/cve-2023-44401/
- https://github.com/silverstripe/silverstripe-graphql/security/advisories/GHSA-jgph-w8rh-xf5p
Note that while the silverstripe/silverstripe-framework releases linked below have commits that are related to `CVE-2023-49783`, that repository is not in any way affected (from a vulnerability or exploitability standpoint) by the CVE, and so the CVE isn't relevant for that repository for …
=> Add CVE details for January Silverstripe CMS patches

firebase/php-jwt/2015-04-02.yaml, gree/jose/2016-08-30.yaml, namshi/jose/2015-03-10.yaml
It's a minor improvement: but the reported url for "Critical vulnerabilities in JSON Web Token libraries" is changed
=> Updated links about jwt critical vulnerability

mediawiki/semantic-media-wiki/CVE-2022-48614.yaml
Reference: https://nvd.nist.gov/vuln/detail/CVE-2022-48614
=>  Add CVE-2022-48614 for mediawiki/semantic-media-wiki 

symfony/framework-bundle/CVE-2022-23601.yaml, symfony/symfony/CVE-2022-23601.yaml
Hi team,
This PR aims to keep the same information related to the vuln CVE-2022-23601, but to format it in a way that makes the fix version more explicit, as according to other sources:
- https://github.com/advisories/GHSA-vvmr-8829-6whx
- https://symfony.com/blog/cve-2022-23601-csrf-token-missing-in-forms
Thanks
=> Refactor affected versions in CVE-2022-23601 to make the fix version more explicit

mdanter/ecc/2024-04-24.yaml
We've requested a CVE from MITRE. We will let you know when one is assigned.
References:
* https://github.com/paragonie/phpecc/releases/tag/v2.0.0
* https://github.com/phpecc/phpecc/issues/289#issuecomment-2074006410
=> Add mdanter/ecc

phpseclib/phpseclib/CVE-2024-27354.yaml, phpseclib/phpseclib/CVE-2024-27355.yaml
Add:
- CVE-2024-27354 https://github.com/advisories/GHSA-hg35-mp25-qf6h  
- CVE-2024-27355 https://github.com/advisories/GHSA-jr22-8qgm-4q87
Fixes: https://github.com/FriendsOfPHP/security-advisories/issues/720
=> phpseclib/phpseclib CVE-2024-27354, CVE-2024-27355

mdanter/ecc/CVE-2024-33851.yaml
See https://github.com/FriendsOfPHP/security-advisories/pull/719#issuecomment-2081383336
=> mdanter/ecc security issue had a CVE id assigned

mdanter/ecc/2024-04-24.yaml, mdanter/ecc/CVE-2024-33851.yaml, paragonie/ecc/CVE-2024-33851.yaml
Context:
https://github.com/FriendsOfPHP/security-advisories/pull/719 - multiple security issues in mdanter/ecc lead to fork in paragonie/ecc and I requested they fill in the CVE id when they have one. I then changed the advisory to include a CVE id in https://github.com/FriendsOfPHP/security-advisories/pull/722
However it turns out there are really two separate advisories:
- https://github.com/advisories/GHSA-346h-749j-r28w original broad issue leading the fork
- https://github.com/advisories/GHSA-3494-cfwf-56hw specific problem with CVE-2024-33851 which applies to mdanter/ecc but also new paragonie/ecc in version 2.0.0 only
So I've reverted the addition of the CVE id to the original advisory, and then added new advisories with the CVE id for the second issue on both packages now.
=> Clean up mess around mdanter/ecc fork and CVE-2024-33851

magento/product-community-edition/CVE-2024-34102.yaml
This PR adds [CVE-2024-34102](https://nvd.nist.gov/vuln/detail/CVE-2024-34102). 
This CVE affects all versions of Magento prior to 2.4.4-p8. Magento versions prior to 2.4.4 are not maintained, there are therefore no fix deployed for those versions.
=> Add CVE-2024-34102 for Magento - Server-Side Request Forgery.

friendsofsymfony1/symfony1/CVE-2024-28859.yaml, friendsofsymfony1/symfony1/CVE-2024-28861.yaml
The current version of [friendsofsymfony1/symfony1](https://github.com/FriendsOfSymfony1/symfony1) is 1.5.9, not 1.15.9. This causes issues with composer audit. Both existing CVEs are affected.
=> Fix incorrect Affected versions for friendsofsymfony1/symfony1

yiisoft/yii2/CVE-2024-4990.yaml
This PR adds the CVE-2024-4990 in `yiisoft/yii2`.
This is my first contribution, I hope I did it right, especially the `branches` key :sweat_smile:
=> Add CVE-2024-4990

nategood/httpful/2024-05-01.yaml
A security issue has been disclosed for the `nategood/httpful` library, leaving all 0.x releases vulnerable. The author of the library has acknowledged the issue in the release notes of the 1.0.0 release:
https://github.com/nategood/httpful/blob/ea02c8aedef70b9a453ce97978d9d7c413972f15/README.md?plain=1#L68-L72
=> nategood/httpful: certificate verification issue

phpoffice/phpexcel/CVE-2015-3542.yaml
The CVE ID is mentioned in the changelog:
* https://github.com/PHPOffice/PHPExcel/blob/1.8/changelog.txt
* https://github.com/PHPOffice/PhpSpreadsheet/blob/master/CHANGELOG.PHPExcel.md
But it looks like it was never published publicly: https://cve.mitre.org/cgi-bin/cvename.cgi?name=2015-3542
=> Add CVE-2015-3542

laravel/framework/CVE-2024-52301.yaml
- Version ranges from GH advisory https://github.com/advisories/GHSA-gv7v-rgg6-548h
- timestamps from fix commits on respective branches
=> Add CVE-2024-52301 in laravel/framework

silverstripe/framework/CVE-2024-47605.yaml, silverstripe/framework/CVE-2024-53277.yaml, silverstripe/framework/SS-2024-002.yaml
All of these were included in the 5.3.8 release: https://github.com/silverstripe/silverstripe-framework/releases/tag/5.3.8
- https://www.silverstripe.org/download/security-releases/cve-2024-47605
- https://github.com/silverstripe/silverstripe-asset-admin/security/advisories/GHSA-7cmp-cgg8-4c82
- https://www.silverstripe.org/download/security-releases/cve-2024-53277
- https://github.com/silverstripe/silverstripe-framework/security/advisories/GHSA-ff6q-3c9c-6cf5
- https://www.silverstripe.org/download/security-releases/ss-2024-002
- https://github.com/silverstripe/silverstripe-framework/security/advisories/GHSA-mqf3-qpc3-g26q
=> Add CVE details for January 2025 Silverstripe CMS patches

validator.php
Following https://github.com/FriendsOfPHP/security-advisories/pull/748
Validates that:
* if time is provided as a string that it can be parsed by PHP
* the provided time isn't in the future (which isn't possible as the time references an existing commit)
=> Validate that time property is valid and not in the future

symfony/ux-live-component/CVE-2025-47946.yaml, symfony/ux-twig-component/CVE-2025-47946.yaml
Related blog post: https://symfony.com/blog/symfony-ux-cve-2025-47946-unsanitized-html-attribute-injection-via-componentattributes
=> Add CVE-2025-47964 for Symfony UX Twig/Live Component
